package ballisticslookuptable;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * This class generates a lookup table of optimal launch parameters (angle, velocity) for a range of distances to a target.
 * The lookup table is generated by simulating trajectories for different launch angles and velocities, and scoring them based on impact angle and time of flight.
 * The best trajectory for each range increment is stored in the lookup table, which can be queried to get the optimal launch parameters for a given range.
 */
public class BallisticsCalculator {

    // TreeMap to store the best launch parameter for each range increment, the key is the range in meters and the value is the best launch parameter for that range
    private TreeMap<Double, LaunchParameter> lookupTable = new TreeMap<>();
    
    // Configuration instance containing all constraints and parameters
    private final BallisticsConfig config;
    
    /**
     * Creates a BallisticsCalculator with default configuration.
     * Time complexity: O(R * A) due to lookup table generation.
     */
    public BallisticsCalculator() {
        this(new BallisticsConfig());
    }
    
    /**
     * Creates a BallisticsCalculator with custom configuration.
     * @param config Configuration object containing all ballistics parameters
     * Time complexity: O(R * A) due to lookup table generation.
     */
    public BallisticsCalculator(BallisticsConfig config) {
        this.config = config;
        config.validate();
        generateLookupTable();
    }

    /**
     * Returns the lookup table, generating it if needed.
     * Time complexity: O(1) if already generated; O(R * A) if it triggers table generation.
     */
    public TreeMap<Double, LaunchParameter> getLookupTable() {
        if (lookupTable.isEmpty()) {
            generateLookupTable();
        }
        return lookupTable;
    }

    /**
     * Builds the lookup table of best launch parameters by range.
     * Time complexity: O(R * A).
     */
    private void generateLookupTable() {
        for (double range = config.getMinRange(); range <= config.getMaxRange(); range += config.getRangeStep()) {
            List<LaunchParameter> parameters = new ArrayList<LaunchParameter>();
            LaunchParameter bestParam = null;
            for (double angle = config.getMinLaunchAngleDeg(); angle <= config.getMaxLaunchAngleDeg(); angle += config.getAngleStep()) {
                LaunchParameter param = new LaunchParameter(angle, range, config.getTargetElevationMeters());
                if (param.getLaunchVelocityMps() <= config.getMinLaunchVelocityMps() || param.getLaunchVelocityMps() > config.getMaxLaunchVelocityMps()) {
                    continue; // Skip trajectories that are not physically possible
                }
                if (param.getImpactAngleDeg() > config.getMinImpactAngle()){
                    continue; // Skip trajectories that are too shallow 
                }
                if ( param.getPeakHeightMeters() > config.getMaxPeakHeight()){
                    continue; // Skip trajectories that are too high
                }
                if ( param.getPeakHeightMeters() < config.getMinPeakHeight()){
                    continue; // Skip trajectories that are too low
                }
                parameters.add(param);
            }
            // calculate normalized score based on impact angle and time of flight
            // normalize impact angle to range -> [0, 1]
            // normalize time of flight to range -> [0, 1]
            double maxImpactAngle = Double.NEGATIVE_INFINITY;
            double minImpactAngle = Double.POSITIVE_INFINITY;
            double maxTimeOfFlight = Double.NEGATIVE_INFINITY;
            double minTimeOfFlight = Double.POSITIVE_INFINITY;
            for (LaunchParameter launchParameter : parameters) {
                if (launchParameter.getImpactAngleDeg() > maxImpactAngle) {
                    maxImpactAngle = launchParameter.getImpactAngleDeg();
                }
                if (launchParameter.getImpactAngleDeg() < minImpactAngle) {
                    minImpactAngle = launchParameter.getImpactAngleDeg();
                }
                if (launchParameter.getTimeOfFlightSeconds() > maxTimeOfFlight) {
                    maxTimeOfFlight = launchParameter.getTimeOfFlightSeconds();
                }
                if (launchParameter.getTimeOfFlightSeconds() < minTimeOfFlight) {
                    minTimeOfFlight = launchParameter.getTimeOfFlightSeconds();
                }
            } 
            
            // TODO: Brainstorm what other factors we could consider for scoring - for example, we could also consider the horizontal velocity at impact, 

            // score = (normalized impact angle) * impactAngleWeight + (normalized time of flight) * timeOfFlightWeight
            // iterate through the list and choose the one with the greatest score
            for (LaunchParameter launchParameter : parameters) {
                double normalizedImpactAngle = 0;
                if (maxImpactAngle != minImpactAngle) {
                    //normalizedImpactAngle = (launchParameter.getImpactAngleDeg() - minImpactAngle) / (maxImpactAngle - minImpactAngle);
                    normalizedImpactAngle = (maxImpactAngle - launchParameter.getImpactAngleDeg()) / (maxImpactAngle - minImpactAngle);
                }

                double normalizedTimeOfFlight = 0;
                if (maxTimeOfFlight != minTimeOfFlight) {
                    //normalizedTimeOfFlight = (launchParameter.getTimeOfFlightSeconds() - minTimeOfFlight) / (maxTimeOfFlight - minTimeOfFlight);
                    normalizedTimeOfFlight = (maxTimeOfFlight - launchParameter.getTimeOfFlightSeconds()) / (maxTimeOfFlight - minTimeOfFlight);
                }   
                double score = (normalizedImpactAngle * config.getImpactAngleWeight()) + (normalizedTimeOfFlight * config.getTimeOfFlightWeight());
                launchParameter.setScore(score);
                if (bestParam == null || launchParameter.getScore() > bestParam.getScore()) {
                    bestParam = launchParameter;
                }
            }
            if (bestParam != null) {
                lookupTable.put(range, bestParam);
            } else {
                // TODO: we could consider adding a default parameter for ranges that don't have a valid trajectory, 
                // for now we will just skip them and they will return null when queried
                //System.err.println("Warning: No valid trajectory found for range " + range);
            }
        }
    }

    /**
     * Returns the best launch parameter for the given range.
     * Time complexity: O(log N).
     */
    public LaunchParameter getBestLaunchParameter(double range) {
        Map.Entry<Double, LaunchParameter> floorEntry = lookupTable.floorEntry(range);
        Map.Entry<Double, LaunchParameter> ceilingEntry = lookupTable.ceilingEntry(range);

        LaunchParameter floorParam = (floorEntry != null) ? floorEntry.getValue() : null;
        LaunchParameter ceilingParam = (ceilingEntry != null) ? ceilingEntry.getValue() : null;

        // which one is closer to the target range? use the closest one as the best parameter for this range increment
        LaunchParameter param = null;
        if (floorParam != null && ceilingParam != null) {
            double floorDiff = Math.abs(range - floorParam.getRangeMeters());
            double ceilingDiff = Math.abs(range - ceilingParam.getRangeMeters());
            param = (floorDiff < ceilingDiff) ? floorParam : ceilingParam;
        } else if (floorParam != null) {
            param = floorParam;
        } else if (ceilingParam != null) {
            param = ceilingParam;
        }
        return param;
    }

}
